version: '3.8'
#Volumes fixos
volumes:
  meta_vol:

networks:
  meta_net:
    driver: bridge

#Services de banco mongo e postgre
services:
  srv-pyspark-notebook:
    image: zul9an9/pyspark-notebook:v1
    container_name: pyspark-notebook
    ports:
    - 8888:8888
   networks:
     - meta_net
   volumes:
    - meta_vol:/app